data:
  train_path: "data/iris.csv"
  target_column: "species"
  test_size: 0.2
  random_state: 42

pipeline:
  transformers:
    - type: "standard_scaler"
      params: {}

model:
  type: "random_forest"
  params:
    n_estimators: 100
    random_state: 42

training:
  test_size: 0.2
  random_state: 42
  model_type: "random_forest"
  cross_validation: 5

output:
  model_dir: "experiments/models"
  predictions_dir: "experiments/predictions"
