data:
  train_path: "data/raw/iris.csv"
  test_path: "data/raw/test.csv"
  processed_dir: "data/processed"
  target_column: "species"
  test_size: 0.2
  random_state: 42

model:
  type: "random_forest"
  params:
    n_estimators: 100
    random_state: 42

training:
  test_size: 0.2
  random_state: 42
  model_type: "random_forest"
  cross_validation: 5

logging:
  level: "INFO"
  save_path: "experiments/logs"

output:
  model_dir: "models"
  predictions_dir: "experiments/predictions"
